// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nakbonjjeajqrzwfgufw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ha2JvbmpqZWFqcXJ6d2ZndWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMzY4NjMsImV4cCI6MjA1MDkxMjg2M30.BB1E-b-A9RbpEbdplTHOFkLqV_3EGz4Upifmwbf_8U0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);